[modules]
autoload=yes

; Preload pjsip and audiosocket
preload => res_pjsip.so
preload => res_audiosocket.so
preload => app_audiosocket.so

; Don't load unused channel drivers
noload => chan_sip.so
noload => chan_skinny.so
noload => chan_mgcp.so
noload => chan_unistim.so
